theme: jekyll-theme-cayman
title: AutoConfigPortScanner
description: IEEE C37.118 Serial Port Scanner and Configuration Loader
github:
  repository_name: GridProtectionAlliance/udp2serial
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
